<?php
$con = mysqli_connect("localhost","root","") or die("problem in connection with mysql");
$db = mysqli_select_db($con,"hospitals") or die("problem in selection of database");
$qry = mysqli_query($con,"select*from hospital");
?>
<html>
<head>
	<title>Openlayer multi Marker</title>
</head>
<body>


<div id="mapdiv"></div>
  
<script src="http://www.openlayers.org/api/OpenLayers.js"></script> 
<script>
map = new OpenLayers.Map("mapdiv");
map.addLayer(new OpenLayers.Layer.OSM());

epsg4326 =  new OpenLayers.Projection("EPSG:4326"); //WGS 1984 projection
projectTo = map.getProjectionObject(); //The map projection (Spherical Mercator)

var lonLat = new OpenLayers.LonLat(73.0161,26.2845).transform(epsg4326, projectTo);

var markers = new OpenLayers.Layer.Markers( "Markers" );
map.addLayer(markers);


var cmark = [73.0161,26.2845];
markers.addMarker(new OpenLayers.Marker(lonLat));      

var zoom=12;
map.setCenter(lonLat, zoom);

var vectorLayer = new OpenLayers.Layer.Vector("Overlay");

// Define an array. This could be done in a seperate js file.
// This tidy formatted section could even be generated by a server-side script (jsonp)
var markers = [
<?php 
while($row = mysql_fetch_array($qry))
{
	echo "[".$row[5].",".$row[4]."]";
	echo ",";
}
?>
];

//Loop through the markers array
for (var i=0; i<markers.length; i++) {
  
   var lon = markers[i][0];
   var lat = markers[i][1];
   
	var feature = new OpenLayers.Feature.Vector(
			new OpenLayers.Geometry.Point( lon, lat ).transform(epsg4326, projectTo),
			{description: "marker number " + i} ,
			{externalGraphic: 'img/marker.png', graphicHeight: 25, graphicWidth: 21, graphicXOffset:-12, graphicYOffset:-25  }
		);             
	vectorLayer.addFeatures(feature);
}                        
map.addLayer(vectorLayer);

popup
   marker.events.register("click", marker, function(e){
   popup = new OpenLayers.Popup.FramedCloud("mypopup",
                         marker.lonlat,
                         new OpenLayers.Size(300, 300),
                         "Here is a hospital",
                         null, true);

map.addPopup(popup);
  }); 
map.setCenter (lonLat, zoom);
</script>

<!-- Isro Project -->
  
</body>
</html>
    